export const teams = [
  {
    name: "Bruins",
    from: "Boston",
    logo: "boston-bruins-logo.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Red Wings",
    from: "Detroit",
    logo: "detroit.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Canadiens",
    from: "Montreal",
    logo: "Montreal_Canadiens.png",
    players: [],
    wins: 10,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Lightning",
    from: "Tampa Bay",
    logo: "lightning.jpeg",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Senators",
    from: "Ottowa",
    logo: "senators.png",
    players: [],
    wins: 1,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Panthers",
    from: "Florida",
    logo: "Unknown.jpeg",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Maple Leafs",
    from: "Toronto",
    logo: "maple leafs.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Sabres",
    from: "Buffalo",
    logo: "sabres.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Atlantic Division",
  },
  {
    name: "Hurricanes",
    from: "Carolina",
    logo: "hurricanes.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Devils",
    from: "New Jersey",
    logo: "devils",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Penguins",
    from: "Pittsburg",
    logo: "penguin.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Islanders",
    from: "New York",
    logo: "islanders.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Capitals",
    from: "Washington",
    logo: "capitals.png",
    players: [],
    wins: 5,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Blue Jackets",
    from: "Columbus",
    logo: "blue jackets.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Rangers",
    from: "New York",
    logo: "rangers.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Flyers",
    from: "Philadelphia",
    logo: "flyers.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Eastern Conference",
    division: "Metropolitan Division",
  },
  {
    name: "Avalanche",
    from: "Colorado",
    logo: "ave.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Stars",
    from: "Dallas",
    logo: "star.jpeg",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Jets",
    from: "Winnipeg",
    logo: "Uknown.jpeg",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Black Hawks",
    from: "Chicago",
    logo: "blackhawks.png",
    players: [],
    wins: 1,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Wild",
    from: "Minnesota",
    logo: "wild.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Mammoth",
    from: "Utah",
    logo: "mammoth.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Blues",
    from: "St. Louis",
    logo: "blues.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Predators",
    from: "Nashville",
    logo: "predators.png",
    players: [],
    wins: 5,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Central Division",
  },
  {
    name: "Ducks",
    from: "Anaheim",
    logo: "ducks.png",
    players: [],
    wins: 1,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Golden Knights",
    from: "Vegas",
    logo: "golden knights.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Kings",
    from: "Los Angeles",
    logo: "kings.png",
    players: [],
    wins: 10,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Kraken",
    from: "Seatle",
    logo: "kraken.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Oilers",
    from: "Edmonton",
    logo: "oilers.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Sharks",
    from: "San Jose",
    logo: "sharks.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Canucks",
    from: "Vancouver",
    logo: "canucks.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
  {
    name: "Flames",
    from: "Calgary",
    logo: "flames.png",
    players: [],
    wins: 0,
    losses: 0,
    otLosses: 0,
    conference: "Western Conference",
    division: "Pacific Division",
  },
];



